// <auto-generated />
using BlazorExommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220513093310_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lenovo Legion T5: een krachtpatser van de nieuwste generatie. Met de Lenovo Legion T5 haalt u een echte gaming krachtpatser in huis. De nieuwste AMD Ryzen 7 processor heeft een turbo kloksnelheid van 4,6 Ghz en maar liefst 8 cores en 16 threads. In combinatie met het werkgeheugen van 16 GB en de snelle 1 TB SSD zorgt dit voor krachtige prestaties. Zo kunt u niet alleen genieten van de nieuwste games, maar is deze desktop ook uiterst geschikt voor taken als rendering, 3D tekenen en foto- en of videobewerking.",
                            ImageUrl = "https://www.megekko.nl/productimg/310442/midi/1_Lenovo-Legion-T5-26AMR5-AMD-Ryzen-7-5800-RTX3070-Desktop-Gaming-PC.jpg",
                            Price = 999.00m,
                            Title = "Lenovo Legion T5 26AMR5 AMD Ryzen 7 5800 RTX3070 Desktop Gaming PC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Deze ScreenON GamePC set is perfect voor de startende gamer. De computer heeft geen losse videokaart maar maakt slim gebruik van een processor met geïntegreerde videochip.",
                            ImageUrl = "https://media.s-bol.com/qMyERAG68o5k/l51OyMM/550x550.jpg",
                            Price = 2.00m,
                            Title = "ScreenON - Gaming Set"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brute kracht en een ongeëvenaarde snelheid komen samen in de Legion Tower 5.",
                            ImageUrl = "https://media.s-bol.com/9pPMv1ApXVRZ/g56q9Xl/550x481.jpg",
                            Price = 3.00m,
                            Title = "Lenovo Legion T5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
